CREATE TABLE PERFIS (
	ID INT NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(50) NOT NULL,
	
	CONSTRAINT PK_PERFIS PRIMARY KEY(ID)
);

INSERT INTO PERFIS(DESCRICAO) VALUES('Administrador');

CREATE TABLE USUARIOS (
	ID INT NOT NULL AUTO_INCREMENT,
	ID_PERFIL INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	SOBRENOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(100) NOT NULL,
	
	CONSTRAINT PK_USUARIOS PRIMARY KEY(ID),
	CONSTRAINT FK_PERFIS FOREIGN KEY(ID_PERFIL) REFERENCES PERFIS(ID)
);

INSERT INTO USUARIOS(ID_PERFIL, NOME, SOBRENOME, CPF, EMAIL, SENHA)
VALUES(1, 'Fábio', 'Faraco', '152.012.597-66', 'f.faraco27@gmail.com', 'admin'); 
	 
CREATE TABLE REQUERENTES (
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	SOBRENOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	DT_REQUISICAO DATE NOT NULL,
	DT_NASCIMENTO DATE NOT NULL,
	LOGRADOURO VARCHAR(100) NOT NULL,
	COMPLEMENTO VARCHAR(100) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	TEL_RESIDENCIAL VARCHAR(20) NOT NULL,
	TEL_CELULAR VARCHAR(20) NOT NULL,
	
	CONSTRAINT PK_REQUERENTES PRIMARY KEY(ID)
);
